### ISSUE TITLE
Essen Schadet der Gesundheit

### ISSUE THREAD

**Issue by Kaycee91** [redcatrp/tracker#17]
**Beschreibe den Bug**
Kidneybohnen oder Pfirsich essen schadet der Kerngesundheit

**Reproduktion**
Schritte um den Bug zu reproduzieren:

Auf die Gesundheitsanzeige achten dann Bohnen oder Pfirsich konsumieren 

**Erwartetes Verhalten**
Das Essen sollte dem Char keinen Schaden zufügen 

**Screenshots**
Videoaufnahme leider Buggy mit Shadowplay

**Comment by Ponjimon** [comment]
Okay, nach etwas nachforschen hab ich rausgefunden, dass das gar kein Bug im eigentlichen Sinne ist, sondern am genutzten Plugin "VORP Metabolism" liegt. Das maximale Leben wird dort auf 150 festgesetzt. Werd schauen, dass ich das anpassen kann.

**Comment by Ponjimon** [comment]
Gefixt in 1.0.4
