### ISSUE TITLE
Stau in Rhodes durch Objekte

### ISSUE THREAD

**Issue by Kaycee91** [redcatrp/tracker#23]
**Beschreibe den Bug**
In Rhodes bildet sich vor der Arztpraxis ein Stau Ursachen suche vielleicht durch die Bilder erkennbar

**Screenshots**

![Stau in Rhodes](https://user-images.githubusercontent.com/38119374/135504850-a12a1063-92fc-4a3f-9932-52d94a86b912.png)
![Ursache 1 Rhodes](https://user-images.githubusercontent.com/38119374/135504856-7817015f-2587-4523-935a-3917962a7823.png)

![Ursache 2 Rhodes](https://user-images.githubusercontent.com/38119374/135504867-e6a616e9-78db-4447-beea-44045e1e3027.png)
![Ursache Rhodes 3](https://user-images.githubusercontent.com/38119374/135504877-ef9fdb0f-4e79-4d46-b439-7fd824bca575.png)

**Comment by Ponjimon** [comment]
Der Baumstumpf lässt sich entfernen, löst aber das Problem nicht. Ich weiß leider nicht, ob die Kutsche sich entfernen lässt, ich konnte jedenfalls noch keinen Hash dafür finden (Müsste dann via `RemoveImap(ID)` bzw auslassen von `RequestImap(ID)` entfernt werden.

**Comment by Ponjimon** [comment]
> Wagon on Rhodes Street: 1033721560
Barrel outside Rhodes Doctor's Office: 945502524
