### ISSUE TITLE
Flackernde Textur am Saint Denis Theater

### ISSUE THREAD

**Issue by Kaycee91** [redcatrp/tracker#31]
**Beschreibe den Bug**

Wenn man auf die Textur am Haupteingang schaut flackert sie 

**Screenshots**
![Theater Saint denis textur Falckern](https://user-images.githubusercontent.com/38119374/135518586-33972da8-9dc7-4965-ab9e-1e99ca3ae98e.png)

**Comment by Ponjimon** [comment]
Die Textur flackert nicht, da sind mehrere Models gleichzeitig geladen

**Comment by Ponjimon** [comment]
Ist gefixt!
